var nameList = [
  'Aaron',
  'Abigail',
  'Adam',
  'Aiden',
  'Alex',
  'Alice',
  'Amelia',
  'Andrew',
  'Anna',
  'Anthony',
  'Aria',
  'Ashley',
  'Ava',
  'Benjamin',
  'Blake',
  'Brandon',
  'Brian',
  'Caleb',
  'Cameron',
  'Charlotte',
  'Chloe',
  'Chris',
  'Claire',
  'Daniel',
  'David',
  'Dylan',
  'Eleanor',
  'Elijah',
  'Ella',
  'Emily',
  'Emma',
  'Ethan',
  'Eva',
  'Felix',
  'Gabriel',
  'Grace',
  'Hannah',
  'Henry',
  'Isaac',
  'Isabella',
  'Jack',
  'Jacob',
  'James',
  'Jasmine',
  'Jason',
  'John',
  'Jordan',
  'Joseph',
  'Joshua',
  'Julia',
  'Kai',
  'Katherine',
  'Kevin',
  'Liam',
  'Lucas',
  'Lucy',
  'Luke',
  'Madeline',
  'Mason',
  'Matthew',
  'Maya',
  'Michael',
  'Mila',
  'Nathan',
  'Nicholas',
  'Noah',
  'Nora',
  'Oliver',
  'Olivia',
  'Owen',
  'Paul',
  'Penelope',
  'Peter',
  'Quinn',
  'Rachel',
  'Rebecca',
  'Ryan',
  'Samuel',
  'Sarah',
  'Sebastian',
  'Sienna',
  'Sophia',
  'Stella',
  'Steven',
  'Taylor',
  'Thomas',
  'Tristan',
  'Victoria',
  'William',
  'Wyatt',
  'Zachary',
  'Adrian',
  'Alina',
  'Amir',
  'Anaya',
  'Ari',
  'Beatrice',
  'Bella',
  'Carlos',
  'Cecilia',
  'Cole',
  'Damian',
  'Daphne',
  'Diego',
  'Elena',
  'Elliot',
  'Emilio',
  'Esme',
  'Freya',
  'Gianna',
  'Hector',
  'Iris',
  'Ivan',
  'Jade',
  'Julian',
  'Kara',
  'Leon',
  'Lila',
  'Lorenzo',
  'Marcus',
  'Nina',
  'Oscar',
  'Pablo',
  'Rafael',
  'Rina',
  'Roman',
  'Sofia',
  'Theo',
  'Valeria',
  'Viktor',
  'Xander',
  'Yasmine',
  'Zane',
];

var messageList = [
  'First!!! 🔥🔥🔥',
  'Who’s watching in 2026?? 👀🙋‍♂️',
  'Let’s gooooo 🚀🚀🚀',
  'W streamer 🔥😎',
  'Hello from Brazil 🇧🇷❤️',
  'Anyone else lagging?? 😭📶',
  'LIKE THE STREAM 👍👍👍',
  'Chat is going crazy 😂😂',
  'This is insane 🤯🔥',
  'Can you shout me out?? 🙏😄',
  'Subscribed!! 🔔❤️',
  'Don’t forget to like 👍💯',
  'Spam W in chat 🔥🔥',
  'Bro no way 😳😳',
  'I’ve been waiting for this 😍⏳',
  'Sound check?? 🔊👂',
  'We love you!!! ❤️❤️❤️',
  'This part is my favorite 😭🔥',
  'Who else is here early? ⏰👀',
  'Chat moving too fast 💨😂',
  'Let him cook 🔥🍳',
  'Mods asleep?? 😈😂',
  'That transition tho 😮✨',
  'OMG 😱😱😱',
  '10/10 stream 💯👏',
  'Where’s everyone from? 🌍👋',
  'This deserves more viewers 🚀📈',
  'Ads again 😩📺',
  'I’m watching at work 👀💼',
  'BEST STREAM EVER 🔥🔥🔥',
];

export function generateRandomNames() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

export function generateRandomMessages() {
  return messageList[Math.floor(Math.random() * messageList.length)];
}
